### ISSUE TITLE
Entities keep staying frozen

### ISSUE THREAD

**Issue by TehPigYT** [TheMiniLuca/Clearlag#4]
I have set my config so that mobs will no longer be frozen after 600 ticks (which is basically 30 seconds).
But for some reason the entities keep being frozen.

Is there a fix to this?

**Comment by TehPigYT** [comment]
Also, the plugin does not load upon server startup.
I am using the latest 1.6.0 version.

**Comment by TheMiniLuca** [comment]
> Also, the plugin does not load upon server startup.
> I am using the latest 1.6.0 version.

I'm sorry for replying late. Could you show me a screenshot of the error log?

**Comment by TehPigYT** [comment]
Here you go
```
[21:07:45 INFO]: [L-Clearlag] Enabling L-Clearlag v1.6.0
[21:07:45 ERROR]: Error occurred while enabling L-Clearlag v1.6.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "java.lang.System.getProperty(String)" is null
        at com.github.theminiluca.clear.lag.plugin.handle.Config.setup(Config.java:47) ~[L-Clearlag.jar:?]
        at com.github.theminiluca.clear.lag.plugin.Clearlag.onEnable(Clearlag.java:40) ~[L-Clearlag.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:07:45 INFO]: [L-Clearlag] Disabling L-Clearlag v1.6.0
[21:07:45 ERROR]: Error occurred while disabling L-Clearlag v1.6.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "com.github.theminiluca.clear.lag.plugin.handle.Language.properties" is null
        at com.github.theminiluca.clear.lag.plugin.handle.Language.getProperties(Language.java:58) ~[L-Clearlag.jar:?]
        at com.github.theminiluca.clear.lag.plugin.Clearlag.onDisable(Clearlag.java:116) ~[L-Clearlag.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:572) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by TheMiniLuca** [comment]
> Here you go
> ```
> [21:07:45 INFO]: [L-Clearlag] Enabling L-Clearlag v1.6.0
> [21:07:45 ERROR]: Error occurred while enabling L-Clearlag v1.6.0 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "java.lang.System.getProperty(String)" is null
>         at com.github.theminiluca.clear.lag.plugin.handle.Config.setup(Config.java:47) ~[L-Clearlag.jar:?]
>         at com.github.theminiluca.clear.lag.plugin.Clearlag.onEnable(Clearlag.java:40) ~[L-Clearlag.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> [21:07:45 INFO]: [L-Clearlag] Disabling L-Clearlag v1.6.0
> [21:07:45 ERROR]: Error occurred while disabling L-Clearlag v1.6.0 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "com.github.theminiluca.clear.lag.plugin.handle.Language.properties" is null
>         at com.github.theminiluca.clear.lag.plugin.handle.Language.getProperties(Language.java:58) ~[L-Clearlag.jar:?]
>         at com.github.theminiluca.clear.lag.plugin.Clearlag.onDisable(Clearlag.java:116) ~[L-Clearlag.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:572) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]```

Are you using the purpur bukkit? Please change to paper bukkit or spigot bukkik and try again

**Comment by TehPigYT** [comment]
Is it required to change the software? It was working with purpur in past versions.
